version: '2'

services:
  mongo-express:
    container_name: 'mongo-express'
    image: 'mongo-express'
    ports:
      - '8090:8081'
    networks:
      - mongo

networks:
  mongo:
    external:
      name: tainan-garbage_mongo-network
